---
kind: pipeline
type: docker
name: docker-build

steps:
  - name: docker
    image: 15cm/drone-kaniko
    settings:
      repo: 15cm/mastodon
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  branch:
    - main
  event:
    - push
    - custom
    - tag
